/*
 * Encoder_config.h
 *
 *  Created on: Jan 17, 2022
 *      Author: 20109
 */

#ifndef ROTARY_ENCODER_ENCODER_CONFIG_H_
#define ROTARY_ENCODER_ENCODER_CONFIG_H_

#define ENCODER_CHANNEL_A_PORT			GPIO_PORTB

#define ENCODER_CHANNEL_A_PIN			GPIO_PIN_0

#define ENCODER_CHANNEL_B_PORT			GPIO_PORTB

#define ENCODER_CHANNEL_B_PIN			GPIO_PIN_1

#define ENCODER_SWITCH_PORT				GPIO_PORTB

#define ENCODER_SWITCH_PIN				GPIO_PIN_1

#endif /* 3__HAL_04__ROTARY_ENCODER_ENCODER_CONFIG_H_ */
