/*
 * ChessClock_HWConfig.h
 *
 *  Created on: Feb 23, 2022
 *      Author: 20109
 */

#ifndef CHESSCLOCK_HWCONFIG_H_
#define CHESSCLOCK_HWCONFIG_H_

#define CHESS_CLOCK_LCD_RS_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_RS_PIN						GPIO_PIN_0

#define CHESS_CLOCK_LCD_RW_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_RW_PIN						GPIO_PIN_1

#define CHESS_CLOCK_LCD_E_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_E_PIN						GPIO_PIN_2

#define CHESS_CLOCK_LCD_D4_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_D4_PIN						GPIO_PIN_3

#define CHESS_CLOCK_LCD_D5_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_D5_PIN						GPIO_PIN_4

#define CHESS_CLOCK_LCD_D6_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_D6_PIN						GPIO_PIN_5

#define CHESS_CLOCK_LCD_D7_PORT						GPIO_PORTA
#define CHESS_CLOCK_LCD_D7_PIN						GPIO_PIN_6

#define CHESS_CLOCK_ENCODER_CH_A_PORT			GPIO_PORTA
#define CHESS_CLOCK_ENCODER_CH_A_PIN			GPIO_PIN_7

#define CHESS_CLOCK_ENCODER_CH_B_PORT			GPIO_PORTA
#define CHESS_CLOCK_ENCODER_CH_B_PIN			GPIO_PIN_8

#define CHESS_CLOCK_ENCODER_SWITCH_PORT			GPIO_PORTA
#define CHESS_CLOCK_ENCODER_SWITCH_PIN			GPIO_PIN_9

#define CHESS_CLOCK_PLAYER_1_SWITCH_PORT		GPIO_PORTA
#define CHESS_CLOCK_PLAYER_1_SWITCH_PIN			GPIO_PIN_10

#define CHESS_CLOCK_PLAYER_2_SWITCH_PORT		GPIO_PORTA
#define CHESS_CLOCK_PLAYER_2_SWITCH_PIN			GPIO_PIN_11


#endif /* CHESSCLOCK_HWCONFIG_H_ */
